### ISSUE TITLE
Pre-populate or skip phone number input in mobile handoff?

### ISSUE THREAD

**Issue by lherman-cs** [berbix/berbix-react#65]
![Screen Shot 2021-06-08 at 2 30 50 PM](https://user-images.githubusercontent.com/15654932/121260387-20f3cc80-c866-11eb-90a0-08b988345a6d.png)

I'd like to skip this form as I already have our user's phone number at this point. Is there a way to skip this?

**Comment by sumdp** [comment]
@lherman-cs as previously stated, please use [support@berbix.com](mailto:support@berbix.com) for any feedback, support, or questions you have regarding the Berbix verify flow.

**Comment by jnnnthnn** [comment]
Thanks @sumdp! I'll close this issue as this is a product-related question which cannot be addressed through an SDK change. (For posterity: one solution would be to change the template configuration to _not_ require mobile verification, such that users on desktop could use Berbix's file upload and camera capture flows.)
